config/routes.rb
Rails.application.routes.draw do
  root "homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :reservations

  resources :rooms

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
    post '/users/sign_in' => 'devise/sessions#create'
    get '/users/account' => 'devise/registrations#show'
  end

  get "room/search", to: "rooms#search"

  resources :users do
    collection do
      get "search"
    end
  end

  get "/rooms/in_area/:area", to: "rooms#in_area"
  get "/rooms/search/:query", to: "rooms#search"
  
  get "room/result", to: "rooms#result", as: "room_result"

  resources :users, only: [:show, :edit, :update]

  
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="Footer">
  <div class="container-fluid">
    <a href="/"><%= image_tag 'logo_img.png', class: 'Footer__logo', alt: 'サイトロゴ' %></a>

    <p class="Footer__copyright">
      Copyright © 2023 All rights reserved
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar Navbar">
    <div class="container-fluid">
      <a href="/"><%= image_tag 'logo_img.png', class: 'Navbar__logo', alt: 'サイトロゴ' %></a>


      <% if user_signed_in? %>
        <div class="btn-group">
          <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar? %>
              <%= image_tag current_user.avatar.url, class: "icon_image", size: "40x40" %>
            <% else %>
              <%= image_tag ("usericon_img.png"), size: "40x40" %>
            <% end %>
            <%= current_user.name %>
          </button>

          <ul class="dropdown-menu DropdownMenu" aria-labelledby="dropdown-button">
            <li class="DropdownMenu__item">
              <%= link_to "施設の新規登録", new_room_path %>
            </li>

            <hr class="DropdownMenu__hr">

            <li class="DropdownMenu__item">
              <a href="/reservations">予約済み一覧</a>
            </li>

            <li class="DropdownMenu__item DropdownMenu__item--middle">
            <%= link_to "登録済み一覧", rooms_path %>
            </li>

            <li class="DropdownMenu__item">
              <%= link_to "アカウント設定", user_path(current_user) %>
            </li>

            <hr class="DropdownMenu__hr">

            <li class="DropdownMenu__item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>

      <% else %>
        <ul class="navbar-nav flex-row align-items-center">
          <li class="nav-item NavItem">
            <%= link_to "ログイン", new_user_session_path, class: 'fw-bold NavItem__link NavItem__link--login' %>
          </li>

          <li class="nav-item NavItem">
            <%= link_to "新規登録", new_user_registration_path, class: 'fw-bold NavItem__link NavItem__link--login' %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_profile.html.erb
<section class="container UserSection">
  <h2>設定</h2>

  <div class="UserContainer">
    <ul class="SideNavigation">
      <li class="SideNavigation__item active">
        <%= link_to "アカウント", users_account_path(current_user) %><br>
      </li>

      <li class="SideNavigation__item ">
        <%= link_to "プロフィール", user_path(current_user) %>
      </li>
    </ul>
  </div>
</section>