config/routes.rb
Rails.application.routes.draw do
  root "homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :reservations

  resources :rooms

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
    post '/users/sign_in' => 'devise/sessions#create'
    get '/users/account' => 'devise/registrations#show'
  end

  get "room/search", to: "rooms#search"

  resources :users do
    collection do
      get "search"
    end
  end

  get "/rooms/in_area/:area", to: "rooms#in_area"
  get "/rooms/search/:query", to: "rooms#search"
  
  get "room/result", to: "rooms#result", as: "room_result"

  resources :users, only: [:show, :edit, :update]

  
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, optional: true
  has_one :reservation
  has_many :reservations
  has_many :reservations, dependent: :destroy

  validates :room_name, presence: true
  validates :body, presence: true
  validates :address, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  mount_uploader :image, ImageUploader

  scope :in_area, ->(area) { where("address LIKE ?", "%#{area}%") }
  scope :search, ->(query) { where("room_name LIKE :query OR body LIKE :query", query: "%#{query}%") }

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :ensure_user, only: [:edit, :update, :destroy]

  def index
    @rooms = Room.all
    @user = current_user
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "施設情報を登録しました"
      redirect_to rooms_path(@room)
    else
      flash.now[:alert] = "施設情報を登録できませんでした"
      render :new
    end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    
    if @room.update(room_params)
      flash[:notice] = "施設情報を更新しました"
      redirect_to room_path
    else
      flash.now[:alert] = "施設情報を更新できませんでした"
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "施設が削除されました"
    redirect_to :rooms
  end

  def in_area
    @rooms = Room.in_area(params[:area])
  end
  
  def search
    @rooms = Room.search(params[:query])
  end
  
  def result
    @rooms = Room.all
    @rooms = @rooms.in_area(params[:area]) if params[:area].present?
    @rooms = @rooms.search(params[:query]) if params[:query].present?
    @count = @rooms.count
  end

  private

  def ensure_user
    @rooms = current_user.rooms
    @room = @rooms.find_by(id:params[:id])
    redirect_to new_room_path unless @room
  end

  def room_params
    params.require(:room).permit(:room_name, :body, :price, :address, :image)
  end


end

app/views/rooms/edit.html.erb
<div class="FormWrapper">
  <section class="FormContainer">
    <h2>施設情報の編集</h2>
    <%= form_with(model: @room, local: true) do |f| %>
      <div class="RoomsForm__input-group">
        <%= f.label :room_name,"施設名" %>
        <%= f.text_field :room_name,placeholder:"施設名を入力" %>
      </div>
      <div class="RoomsForm__input-group">
        <%= f.label :body,"施設詳細" %>
        <%= f.text_area :body,placeholder:"施設詳細を入力" %>
      </div>
      <div class="RoomsForm__input-group">
        <%= f.label :price,"料金" %>
        <%= f.number_field :price,placeholder:"一日あたりの料金を入力" %>
      </div>
      <div class="RoomsForm__input-group">
        <%= f.label :address,"住所" %>
        <%= f.text_field :address,placeholder:"住所を入力" %>
      </div>
      <div class="RoomsForm__input-group">
        <%= f.label :image,"施設画像" %>
        <%= f.file_field :image %>
      </div>
      
      <ul>
        <li><%= f.submit "保存" %></li>
        <li><%= link_to "キャンセル", :rooms %></li>
      </ul>
    <% end %>
  </section>
</div>

app/views/rooms/index.html.erb
<section class="container OwnRoomsContainer">
  <h2>登録済み一覧</h2>

  <div class="table-responsive">
    <table class="table align-middle OwnRoomsTable">
      <thead>
        <tr>
          <th>画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th>料金</th>
          <th>住所</th>
          <th>作成日</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
      <% @rooms.each do |room| %>
        <% if room.user_id == current_user.id %>
        <tr>
          <td>
          <% if room.image? %>
            <%= image_tag room.image.url, class: "hotel_image", size: "120x70" %>
          <% else %>
            <%= image_tag ("hotel_img.png"), size: "120x70" %>
          <% end %>
          </td>
          <td><%= link_to "#{room.room_name}", {controller: 'rooms', action: 'show', id: room.id} %></td>
          <td> <%= room.body %></td>
          <td class="text-nowrap"><%= room.price %></td>
          <td class="text-nowrap"><%= room.address %></td>
          <td class="text-nowrap"><%= room.created_at&.strftime("%Y/%m/%d") %></td>
          <% if room.user == current_user %>
            <td><%= link_to "編集", edit_room_path(room) %></td>
            <td><%= link_to "削除" , room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>

  </div>
</section>

app/views/rooms/new.html.erb
<div class="container">
  <section class="FormContainer">
    <h2>新規登録</h2>
    <%= form_with(model: @room, local: true) do |f| %>
      <div class="col">
        <%= f.label :room_name,"施設名" %>
        <%= f.text_field :room_name,placeholder:"施設名を入力" %>
      </div>
      <div class="col">
        <%= f.label :body,"施設詳細" %>
        <%= f.text_area :body,placeholder:"施設詳細を入力" %>
      </div>
      <div class="col">
        <%= f.label :price,"料金" %>
        <%= f.number_field :price,placeholder:"一日あたりの料金を入力" %>
      </div>
      <div class="col">
        <%= f.label :address,"住所" %>
        <%= f.text_field :address,placeholder:"住所を入力" %>
      </div>
      <div class="col">
        <%= f.label :image,"施設画像" %>
        <%= f.file_field :image %>
      </div>
      
      <ul>
        <li><%= f.submit "保存" %></li>
        <li><%= link_to "キャンセル", :rooms %></li>
      </ul>
    <% end %>
  </section>
</div>

app/views/rooms/result.html.erb
<div class="container">
  <div class="search-field">
    <%= form_tag room_result_path, method: :get do %>
      <%= label_tag :area, "エリア検索" %>
      <%= text_field_tag :area, params[:area], placeholder: "エリア名を入力" %>
      <%= label_tag :query, "フリーワード検索" %>
      <%= text_field_tag :query, params[:query], placeholder: "キーワード名を入力" %>
      <%= submit_tag "検索" %>
    <% end %>
  </div>

  <div class="search-results">
    <% if @rooms.present? %>
      <h3>検索結果：<%= @count %>件</h3>
      <div class="card" style="width: 18rem;" >
        <% @rooms.each do |room| %>
          <div class="room_image">
          <% if room.image? %>
            <%= image_tag room.image.url, class: "hotel_image", size: "200x150" %>
          <% else %>
            <%= image_tag ("hotel_img.png"), size: "200x150" %>
          <% end %>
          </div>
          <div class="card-body">
            <h2 class="card-title"><%= room.room_name %></h2>
            <p class="card-text"><%= room.body %></p>
            <p class="card-text"><%= room.address %></p>
            <p class="card-text">料金:¥ <%= room.price %>~</p>
            <%= link_to "詳細ページへ", {controller: 'rooms', action: 'show', id: room.id} %>
          </div>
        <% end %>
      </div> 
    <% else %>
      <h3>検索結果：０件</h3>
      <%= link_to "戻る", :back %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
<h3>施設詳細</h3>

<%= render "shared/error", obj: @reservation %>

<div>
  <ul>
    <li><%= link_to "戻る", :back %></li>
    <li><%= link_to "編集する", edit_room_path(@room) %></li>
  </ul>
</div>


<%= form_with model: @reservation, method: :get, url: new_reservation_path do |f| %>
<table>
  <tr>
    <th>施設画像</th>
    <td>
    <% if @room.image? %>
      <%= image_tag @room.image.url, class: "hotel_image", size: "200x150" %>
    <% else %>
      <%= image_tag ("hotel_img.png"), size: "200x150" %>
    <% end %>
    </td>
  </tr>
  <tr>
    <th>施設名</th>
    <td><%= @room.room_name %></td>
  </tr>
  <tr>
    <th>施設詳細</th>
    <td><%= @room.body %></td>
  </tr>
  <tr>
    <th>料金</th>
    <td><%= @room.price %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @room.address %></td>
  </tr>
</table>

  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :price, value: @room.price %>
  <%= f.hidden_field :room_name, value: @room.room_name %>
  <%= f.hidden_field :image, value: @room.image%>
  <%= f.hidden_field :body, value: @room.body %>

  <label>チェックイン</label>
    <%= f.date_field :start_date, required: true%>

  <label>チェックアウト</label>
    <%= f.date_field :end_date, required: true%>

  <label>人数</label>
    <%= f.text_field :people, required: true%>

  <%= f.submit "予約する"%>
<% end %>
</div>